# Journal Components

[[journal_slides]]
caption = "Journal 1"
description = ""
img = "frontiers.jpg"
link = "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3931231/"

[[journal_slides]]
caption = "Journal 2"
description = ""
img = "journal_archives_of_general_psychiatry.jpg"
link = "https://pubmed.ncbi.nlm.nih.gov/20819990/"

[[journal_slides]]
caption = "Journal 3"
description = ""
img = "journal_ieee_tmi.jpg"
link = "https://ieeexplore.ieee.org/abstract/document/6630106/"

[[journal_slides]]
caption = "Journal 4"
description = ""
img = "journal_Nature-Communications.jpg"
link = "https://www.nature.com/articles/s41467-017-01285-x"

[[journal_slides]]
caption = "Journal 5"
description = ""
img = "journal_neuroimage.jpg"
link = "https://www.sciencedirect.com/science/article/abs/pii/S1053811917305839"

[[journal_slides]]
caption = "Journal 6"
description = ""
img = "journal_pattern_recognition_letters.gif"
link = "https://www.sciencedirect.com/science/article/abs/pii/S0167865516300861"

[[journal_slides]]
caption = "Journal 7"
description = ""
img = "NeurIPS_logo_stacked.png"
link = "https://proceedings.neurips.cc//paper_files/paper/2020/hash/bc047286b224b7bfa73d4cb02de1238d-Abstract.html"

[[journal_slides]]
caption = "Journal 8"
description = ""
img = "neuron.jpg"
link = "https://www.sciencedirect.com/science/article/pii/S0896627321002312"

[[journal_slides]]
caption = "Journal 9"
description = ""
img = "plos_one.jpg"
link = "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0156436"

[[journal_slides]]
caption = "Journal 10"
description = ""
img = "sr_ysrHSfp.jpg"
link = "https://www.nature.com/articles/s41598-020-74054-4"

# Teaching Courses Components

[[teaching_course]]
name = "Image Processing for Medical Applications"
status = "Active"
code = "ENGR-E 535/545 || CSCI-B 456"
level = "Graduate"
semester = "Spring 2017-2025"
prerequisite = "One programming course, linear algebra and calculus are required. Any machine learning or computer vision course would be helpful, but not necessary."
description = "Learn how to build intelligent algorithms and software for medical imaging that can help medical doctors to treat their patients and researchers to understand how the body works. Students will be familiarized with algorithmic techniques such as tracking, denoising, warping, segmentation, model fitting, optimization and interactive visualization of medical datasets."
link = "_static/others/IPMA_Spring2018.pdf"

[[teaching_course]]
name = "Intro to Neuro-Engineering"
status = "Active"
code = "ISE-ENGR-E506"
level = "Graduate"
semester = "Fall 2018-2024"
prerequisite = "None"
description = "The students will learn key concepts of neuroengineering. For example what is plasticity. Furthermore you will learn how to build cool machines for neuroengineering applications but more importantly understand the biology and anatomy of human intelligence"
link = "_static/others/ITIN_Promo.pdf"

[[teaching_course]]
name = "Intelligent Systems I"
status = "Legacy"
code = "ISE - ENGR – E221"
level = "Undergraduate"
semester = "Fall 2017"
prerequisite = "Calc I (M211); Calc II (M212); Physics I (P221); Software systems engineering (ENGR – E-111)"
description = "This course introduces important concepts about intelligent systems. It provides a basis in mathematical tools and algorithms used in AI and machine learning. It introduces optimization techniques used in Intelligent Systems II. It will describe many current examples and how they are implemented in cloud systems. The course is based on Python for data analytics."
link = ""